### ISSUE TITLE
create version for ursa and forge

### ISSUE THREAD

**Issue by coolaj86** [anatolsommer/letiny#1]
As we discussed in email, I agree it would be a good idea to create two modules. I'd like to suggest calling them by these names:
- `letsencrypt-forge`
- `letsencrypt-ursa`

I'm creating a wrapper for [`node-letsencrypt`](https://github.com/Daplie/node-letsencrypt) right now to use the code as is. Then I'll be forking it as `letsencrypt-ursa` and at least get key generation to use ursa in that module.

Perhaps we could then merge your cli code into `node-letsencrypt`, add you as an author, and have it work for all three backends? (including `letsencrypt-python`, which is redundant in a sense, but whatever).

**Comment by anatolsommer** [comment]
please see https://github.com/anatolsommer/letiny/issues/3#issuecomment-164843437
