### ISSUE TITLE
fetch urls from directory

### ISSUE THREAD

**Issue by coolaj86** [anatolsommer/letiny#2]
Currently the values are hard coded (https://github.com/Daplie/letsencrypt-forge/blob/master/lib/client.js#L112), but they should be retrieved from 
- https://acme-v01.api.letsencrypt.org/directory

I'll probably come back around to pull request on this.

**Comment by coolaj86** [comment]
I've got this in my branch, but it's not something that can be PR'd directly.

**Comment by anatolsommer** [comment]
fixed in https://github.com/anatolsommer/letiny/tree/v0.1.0-beta
