### ISSUE TITLE
account creation in-progress

### ISSUE THREAD

**Issue by coolaj86** [anatolsommer/letiny#3]
I'm working on a version of account creation and restoration that uses the same directory structure and conventions as the official python client.

I don't know if I'll finish it tonight and I have a road trip ahead of me tomorrow, but I'll have it done by Wednesday night for sure. In fact, I'll probably have all of the file handling done by Wednesday night (PST).

**Comment by coolaj86** [comment]
making good progress, I'll probably have it done within a few hours, actually

**Comment by coolaj86** [comment]
Getting really close, but I'm having to do some refactoring.

Basically splitting `getCert` into three functions: `getKeys`, `requestCert`, and `writeFiles`.

Here are some changes I'm making:

```
rename
options.challenge => options.setChallenge (there also needs to be an options.getChallenge for express)
options.accountKeyPairPEM => options.accountPrivateKeyPem
options.privateKey => options.domainPrivateKeyPem

check at call time (fail earlier)
options.email
options.agreeTerms
options.setChallenge
options.webroot
options.newReg
```

also there are some sync / async errors

I've got a branch `handshake-only` with my updates so far:
https://github.com/Daplie/letsencrypt-forge/blob/89ef51733871e602ad8b77f99b1512058a8a1c66/lib/client.js

Still working on it.

**Comment by coolaj86** [comment]
Okay, I've got the accounts complete in my branch, here's how to test:

```
git clone git@github.com:Daplie/node-letsencrypt.git
pushd node-letsencrypt
git checkout ursa
npm install
```

```
pushd node_modules
git clone git@github.com:Daplie/letsencrypt-forge.git
git checkout handshake-only
npm install
popd
```

```
# NOTE: need to edit examples/ursa.js to change example.com to your test domain
node examples/ursa.js
```

domain registration should be done in a few minutes, I think

**Comment by coolaj86** [comment]
Okay. I got more than just accounts!!!

Everything is complete except for writing the certificates to disk.

Also, all of the crypto is extracted out so that it can use either `ursa` or `forge` (which also means you can easily integrate your `fork` logic into the crypto wrapper).

TODO:
- [ ] get your version of the CLI working again
- [ ] pass argument to use either `forge` or `usra`
- [ ] save certificates to disk and update `renewal.conf` (parser and stringifier is already complete)

But now I need to go to sleep for a few hours. :-)

**Comment by anatolsommer** [comment]
I think we are trying to achieve the same thing but in very different ways.

I actually want to keep letiny as simple as possible and create additional libraries (using letiny) for any additional functionality (unix philosophy).

My idea was to create a letiny-ursa library that generates keys using ursa and calling letiny (already added the required options for this yesterday). Another library could be letiny-express containing middleware for the acme challenge and some code to obtain/renew certificates and fireing an event when certs are available.

This should allow everyone to use exactly what's needed:
letiny: easy to use, nothing needs to be compiled but runs slow on cheap hardware
letiny-ursa: does the same but faster using openssl bindings
letiny-express: uses letiny or letiny-ursa and provides anything related to express

Don't you think it would be smarter to handle it this way?

**Comment by coolaj86** [comment]
I agree with you entirely, and that's actually what I'm trying to do, but I don't think I stated it well.

(and also certain thoughts were less informed before I understood the code better)
