### ISSUE TITLE
about sharp-bang

### ISSUE THREAD

**Issue by i5ting** [anatolsommer/letiny#7]
letiny -e me@example.com -m -d example.com,www.example.com --agree -w .
zsh: /Users/sang/.nvm/versions/node/v7.2.1/bin/letiny: bad interpreter: /usr/local/bin/node: no such file or directory

may be we can use like this, a common way 

```
#!/usr/bin/env node
```

**Comment by anatolsommer** [comment]
You are absolutely right, thank you!
